# ch01_HomeWork_0

自己 出 3, 5, 10 變數線性方程組共3題， 以numpy 求解 (含驗算)， 

並撰寫文件(含心得討論)。 
 

In [7]:
import numpy as np

## 3 變數

In [63]:
n= 3

np.random.seed(0) #設隨機種子碼，使產生的方程式固定

A= np.random.randint(-5,5,size=(n,n))  #產生n*n的矩陣，數字範圍在(-5,5)

np.random.seed(1) #設隨機種子碼，使產生的方程式固定

b= np.random.randint(-5,5,size=(n,1))  #產生1*n的矩陣，數字範圍在(-5,5)
 
x= np.linalg.solve(A, b) #解方程式

print(f'n= {n},  \nA= {A} \nb= {b} \nx= {x}') #顯示結果

n= 3,  
A= [[ 0 -5 -2]
 [-2  2  4]
 [-2  0 -3]] 
b= [[0]
 [3]
 [4]] 
x= [[-1.75806452]
 [ 0.06451613]
 [-0.16129032]]


In [64]:
#驗算
A @ x

array([[0.],
       [3.],
       [4.]])

## 5 變數

In [73]:
n= 5 

np.random.seed(2) 

A= np.random.randint(-5,5,size=(n,n)) 

np.random.seed(3)

b= np.random.randint(-5,5,size=(n,1)) 

x= np.linalg.solve(A, b) 

print(f'n= {n},  \nA= {A} \nb= {b} \nx= {x}') 

n= 5,  
A= [[ 3  3  1 -3  3]
 [ 2 -3 -4  0 -1]
 [-1  0  2 -2  1]
 [-1 -2  2  1 -4]
 [-2  0  3 -1  1]] 
b= [[ 3]
 [ 4]
 [-2]
 [ 3]
 [ 3]] 
x= [[ 6.13235294]
 [-6.04411765]
 [ 5.38235294]
 [ 5.75      ]
 [ 4.86764706]]


In [75]:
#驗算
A @ x #  == b

array([[ 3.],
       [ 4.],
       [-2.],
       [ 3.],
       [ 3.]])

## 10 變數

In [76]:
n= 10 

np.random.seed(3) 

A= np.random.randint(-5,5,size=(n,n)) 

np.random.seed(4) 

b= np.random.randint(-5,5,size=(n,1)) 

x= np.linalg.solve(A, b) 

print(f'n= {n},  \nA= {A} \nb= {b} \nx= {x}') 

n= 10,  
A= [[ 3  4 -2  3  3 -5  0 -2  4  4]
 [ 0  2  1 -5 -1  2  3 -4  1 -3]
 [-3 -4 -2  0  3 -4  3  2  3 -4]
 [-5  0 -1 -4  0 -1  2  1 -5 -5]
 [ 4 -3 -1  0  3  3  2  0 -4 -4]
 [-4  0  0  2 -1 -2 -5 -5 -5 -5]
 [-3 -3  2 -5  0 -5 -4 -1 -4 -3]
 [-3 -1  3 -5  1 -5 -1 -4  0 -4]
 [ 3  3  2 -5 -5  4 -4  2  3  2]
 [-1 -5 -5 -1 -2 -5  3 -3  2 -3]] 
b= [[ 2]
 [ 0]
 [-4]
 [ 3]
 [ 2]
 [ 3]
 [-3]
 [ 4]
 [ 2]
 [ 2]] 
x= [[ 5.32709399]
 [ 3.2380935 ]
 [ 6.57094315]
 [ 4.47347373]
 [-7.44088003]
 [-6.07124059]
 [ 4.54256673]
 [ 3.40883883]
 [-1.82289057]
 [-5.28412846]]


In [80]:
#驗算
A @ x  #== b

array([[ 2.],
       [ 0.],
       [-4.],
       [ 3.],
       [ 2.],
       [ 3.],
       [-3.],
       [ 4.],
       [ 2.],
       [ 2.]])