In [1]:
from sympy import *

# 1

In [2]:
x, n = symbols('x, n')

In [56]:
f = x**10
f.integrate((x,0,n))

n**11/11

In [54]:
f = x
Sum(f, (x, 0, n)).doit()

n**2/2 + n/2

In [57]:
Sum(f, (x, 0, n)).doit()

n**11/11 + n**10/2 + 5*n**9/6 - n**7 + n**5 - n**3/2 + 5*n/66

In [58]:
f = (x-1)**10
Sum(f, (x, 0, n)).doit()

n**11/11 - n**10/2 + 5*n**9/6 - n**7 + n**5 - n**3/2 + 5*n/66 + 1

In [61]:
f = x**10*sp.exp(-x)
f.integrate(x).simplify()

-(x**10 + 10*x**9 + 90*x**8 + 720*x**7 + 5040*x**6 + 30240*x**5 + 151200*x**4 + 604800*x**3 + 1814400*x**2 + 3628800*x + 3628800)*exp(-x)

In [69]:
x, y = sp.symbols('x y')
f = sp.exp(-((x-1)**2) + (y+1)**2)
f.diff(x)

(2 - 2*x)*exp(-(x - 1)**2 + (y + 1)**2)

In [70]:
f.diff(y)

(2*y + 2)*exp(-(x - 1)**2 + (y + 1)**2)

In [75]:
f.diff(x).diff(y)

(2 - 2*x)*(2*y + 2)*exp(-(x - 1)**2 + (y + 1)**2)

In [74]:
fx = f.diff(x)
fy = f.diff(y)
sp.solve((fx, fy))

[{x: 1, y: -1}]

In [78]:
f.subs(x, 1).subs(y, -1)

1

In [81]:
%matplotlib qt
q = sp.plotting.plot3d(f, xlabel='x', ylabel='y', title=f'z = f(x,y) = {f}', show = False)
q.show()

In [88]:
j = sp.I
j**j.evalf()
## 參考資料 j 的 j次方 https://kknews.cc/zh-tw/education/z6vpk6g.html

I**(1.0*I)

# 2

In [4]:
from numpy import *

In [5]:
A = array([[5,1],[1,5]])
linalg.inv(A)

array([[ 0.20833333, -0.04166667],
       [-0.04166667,  0.20833333]])

In [6]:
b = array([10,20])
A@b

array([ 70, 110])

In [7]:
b@A

array([ 70, 110])

In [8]:
transpose(b)@A

array([ 70, 110])

In [9]:
e_vals,e_vecs = linalg.eig(A)
e_vecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [10]:
A*transpose(b)

array([[ 50,  20],
       [ 10, 100]])

In [11]:
f = A*x - b
f

array([[5*x - 10, x - 20],
       [x - 10, 5*x - 20]], dtype=object)

In [12]:
c = array([5/4, 15/4])
A@c == b

array([ True,  True])

# 3

In [13]:
import scipy.stats as st
import matplotlib.pyplot as plt
import sympy as sp

In [14]:
π = sp.pi
ϕ = sp.exp(-x**2/2) / sp.sqrt(2*π)
ϕ

sqrt(2)*exp(-x**2/2)/(2*sqrt(pi))

In [15]:
ϕ.integrate((x, -2, 2))

erf(sqrt(2))

In [16]:
ϕ.integrate(x)

erf(sqrt(2)*x/2)/2

In [17]:
m = x*ϕ
m

sqrt(2)*x*exp(-x**2/2)/(2*sqrt(pi))

In [32]:
#μ = x*ϕ.integrate(x)

integrate(m, x)
#μ.evalf()

-sqrt(2)*exp(-x**2/2)/(2*sqrt(pi))

In [19]:
sp.limit

<function sympy.series.limits.limit(e, z, z0, dir='+')>

In [20]:
ϕ

sqrt(2)*exp(-x**2/2)/(2*sqrt(pi))

In [24]:
var = ((x-μ)**2*ϕ).integrate(x)

KeyboardInterrupt: 

In [23]:
var.evalf()

-0.398942280401433*x*exp(-x**2/2) + 0.5*erf(sqrt(2)*x/2)

In [37]:
f = (((x-0)/1)**3 * ϕ).integrate(x)
#integrate(x**3*ϕ, x)
f

(-sqrt(2)*x**2 - 2*sqrt(2))*exp(-x**2/2)/(2*sqrt(pi))

In [42]:
(x**4*ϕ).integrate(x).simplify()

(-sqrt(2)*x**3 - 3*sqrt(2)*x + 3*sqrt(pi)*exp(x**2/2)*erf(sqrt(2)*x/2))*exp(-x**2/2)/(2*sqrt(pi))

In [107]:
entropy = (sp.log(1/ϕ, sp.E)*ϕ).integrate(x)

ValueError: Invalid limits given: (array([-3.        , -2.99399399, -2.98798799, -2.98198198, -2.97597598,
       -2.96996997, -2.96396396, -2.95795796, -2.95195195, -2.94594595,
       -2.93993994, -2.93393393, -2.92792793, -2.92192192, -2.91591592,
       -2.90990991, -2.9039039 , -2.8978979 , -2.89189189, -2.88588589,
       -2.87987988, -2.87387387, -2.86786787, -2.86186186, -2.85585586,
       -2.84984985, -2.84384384, -2.83783784, -2.83183183, -2.82582583,
       -2.81981982, -2.81381381, -2.80780781, -2.8018018 , -2.7957958 ,
       -2.78978979, -2.78378378, -2.77777778, -2.77177177, -2.76576577,
       -2.75975976, -2.75375375, -2.74774775, -2.74174174, -2.73573574,
       -2.72972973, -2.72372372, -2.71771772, -2.71171171, -2.70570571,
       -2.6996997 , -2.69369369, -2.68768769, -2.68168168, -2.67567568,
       -2.66966967, -2.66366366, -2.65765766, -2.65165165, -2.64564565,
       -2.63963964, -2.63363363, -2.62762763, -2.62162162, -2.61561562,
       -2.60960961, -2.6036036 , -2.5975976 , -2.59159159, -2.58558559,
       -2.57957958, -2.57357357, -2.56756757, -2.56156156, -2.55555556,
       -2.54954955, -2.54354354, -2.53753754, -2.53153153, -2.52552553,
       -2.51951952, -2.51351351, -2.50750751, -2.5015015 , -2.4954955 ,
       -2.48948949, -2.48348348, -2.47747748, -2.47147147, -2.46546547,
       -2.45945946, -2.45345345, -2.44744745, -2.44144144, -2.43543544,
       -2.42942943, -2.42342342, -2.41741742, -2.41141141, -2.40540541,
       -2.3993994 , -2.39339339, -2.38738739, -2.38138138, -2.37537538,
       -2.36936937, -2.36336336, -2.35735736, -2.35135135, -2.34534535,
       -2.33933934, -2.33333333, -2.32732733, -2.32132132, -2.31531532,
       -2.30930931, -2.3033033 , -2.2972973 , -2.29129129, -2.28528529,
       -2.27927928, -2.27327327, -2.26726727, -2.26126126, -2.25525526,
       -2.24924925, -2.24324324, -2.23723724, -2.23123123, -2.22522523,
       -2.21921922, -2.21321321, -2.20720721, -2.2012012 , -2.1951952 ,
       -2.18918919, -2.18318318, -2.17717718, -2.17117117, -2.16516517,
       -2.15915916, -2.15315315, -2.14714715, -2.14114114, -2.13513514,
       -2.12912913, -2.12312312, -2.11711712, -2.11111111, -2.10510511,
       -2.0990991 , -2.09309309, -2.08708709, -2.08108108, -2.07507508,
       -2.06906907, -2.06306306, -2.05705706, -2.05105105, -2.04504505,
       -2.03903904, -2.03303303, -2.02702703, -2.02102102, -2.01501502,
       -2.00900901, -2.003003  , -1.996997  , -1.99099099, -1.98498498,
       -1.97897898, -1.97297297, -1.96696697, -1.96096096, -1.95495495,
       -1.94894895, -1.94294294, -1.93693694, -1.93093093, -1.92492492,
       -1.91891892, -1.91291291, -1.90690691, -1.9009009 , -1.89489489,
       -1.88888889, -1.88288288, -1.87687688, -1.87087087, -1.86486486,
       -1.85885886, -1.85285285, -1.84684685, -1.84084084, -1.83483483,
       -1.82882883, -1.82282282, -1.81681682, -1.81081081, -1.8048048 ,
       -1.7987988 , -1.79279279, -1.78678679, -1.78078078, -1.77477477,
       -1.76876877, -1.76276276, -1.75675676, -1.75075075, -1.74474474,
       -1.73873874, -1.73273273, -1.72672673, -1.72072072, -1.71471471,
       -1.70870871, -1.7027027 , -1.6966967 , -1.69069069, -1.68468468,
       -1.67867868, -1.67267267, -1.66666667, -1.66066066, -1.65465465,
       -1.64864865, -1.64264264, -1.63663664, -1.63063063, -1.62462462,
       -1.61861862, -1.61261261, -1.60660661, -1.6006006 , -1.59459459,
       -1.58858859, -1.58258258, -1.57657658, -1.57057057, -1.56456456,
       -1.55855856, -1.55255255, -1.54654655, -1.54054054, -1.53453453,
       -1.52852853, -1.52252252, -1.51651652, -1.51051051, -1.5045045 ,
       -1.4984985 , -1.49249249, -1.48648649, -1.48048048, -1.47447447,
       -1.46846847, -1.46246246, -1.45645646, -1.45045045, -1.44444444,
       -1.43843844, -1.43243243, -1.42642643, -1.42042042, -1.41441441,
       -1.40840841, -1.4024024 , -1.3963964 , -1.39039039, -1.38438438,
       -1.37837838, -1.37237237, -1.36636637, -1.36036036, -1.35435435,
       -1.34834835, -1.34234234, -1.33633634, -1.33033033, -1.32432432,
       -1.31831832, -1.31231231, -1.30630631, -1.3003003 , -1.29429429,
       -1.28828829, -1.28228228, -1.27627628, -1.27027027, -1.26426426,
       -1.25825826, -1.25225225, -1.24624625, -1.24024024, -1.23423423,
       -1.22822823, -1.22222222, -1.21621622, -1.21021021, -1.2042042 ,
       -1.1981982 , -1.19219219, -1.18618619, -1.18018018, -1.17417417,
       -1.16816817, -1.16216216, -1.15615616, -1.15015015, -1.14414414,
       -1.13813814, -1.13213213, -1.12612613, -1.12012012, -1.11411411,
       -1.10810811, -1.1021021 , -1.0960961 , -1.09009009, -1.08408408,
       -1.07807808, -1.07207207, -1.06606607, -1.06006006, -1.05405405,
       -1.04804805, -1.04204204, -1.03603604, -1.03003003, -1.02402402,
       -1.01801802, -1.01201201, -1.00600601, -1.        , -0.99399399,
       -0.98798799, -0.98198198, -0.97597598, -0.96996997, -0.96396396,
       -0.95795796, -0.95195195, -0.94594595, -0.93993994, -0.93393393,
       -0.92792793, -0.92192192, -0.91591592, -0.90990991, -0.9039039 ,
       -0.8978979 , -0.89189189, -0.88588589, -0.87987988, -0.87387387,
       -0.86786787, -0.86186186, -0.85585586, -0.84984985, -0.84384384,
       -0.83783784, -0.83183183, -0.82582583, -0.81981982, -0.81381381,
       -0.80780781, -0.8018018 , -0.7957958 , -0.78978979, -0.78378378,
       -0.77777778, -0.77177177, -0.76576577, -0.75975976, -0.75375375,
       -0.74774775, -0.74174174, -0.73573574, -0.72972973, -0.72372372,
       -0.71771772, -0.71171171, -0.70570571, -0.6996997 , -0.69369369,
       -0.68768769, -0.68168168, -0.67567568, -0.66966967, -0.66366366,
       -0.65765766, -0.65165165, -0.64564565, -0.63963964, -0.63363363,
       -0.62762763, -0.62162162, -0.61561562, -0.60960961, -0.6036036 ,
       -0.5975976 , -0.59159159, -0.58558559, -0.57957958, -0.57357357,
       -0.56756757, -0.56156156, -0.55555556, -0.54954955, -0.54354354,
       -0.53753754, -0.53153153, -0.52552553, -0.51951952, -0.51351351,
       -0.50750751, -0.5015015 , -0.4954955 , -0.48948949, -0.48348348,
       -0.47747748, -0.47147147, -0.46546547, -0.45945946, -0.45345345,
       -0.44744745, -0.44144144, -0.43543544, -0.42942943, -0.42342342,
       -0.41741742, -0.41141141, -0.40540541, -0.3993994 , -0.39339339,
       -0.38738739, -0.38138138, -0.37537538, -0.36936937, -0.36336336,
       -0.35735736, -0.35135135, -0.34534535, -0.33933934, -0.33333333,
       -0.32732733, -0.32132132, -0.31531532, -0.30930931, -0.3033033 ,
       -0.2972973 , -0.29129129, -0.28528529, -0.27927928, -0.27327327,
       -0.26726727, -0.26126126, -0.25525526, -0.24924925, -0.24324324,
       -0.23723724, -0.23123123, -0.22522523, -0.21921922, -0.21321321,
       -0.20720721, -0.2012012 , -0.1951952 , -0.18918919, -0.18318318,
       -0.17717718, -0.17117117, -0.16516517, -0.15915916, -0.15315315,
       -0.14714715, -0.14114114, -0.13513514, -0.12912913, -0.12312312,
       -0.11711712, -0.11111111, -0.10510511, -0.0990991 , -0.09309309,
       -0.08708709, -0.08108108, -0.07507508, -0.06906907, -0.06306306,
       -0.05705706, -0.05105105, -0.04504505, -0.03903904, -0.03303303,
       -0.02702703, -0.02102102, -0.01501502, -0.00900901, -0.003003  ,
        0.003003  ,  0.00900901,  0.01501502,  0.02102102,  0.02702703,
        0.03303303,  0.03903904,  0.04504505,  0.05105105,  0.05705706,
        0.06306306,  0.06906907,  0.07507508,  0.08108108,  0.08708709,
        0.09309309,  0.0990991 ,  0.10510511,  0.11111111,  0.11711712,
        0.12312312,  0.12912913,  0.13513514,  0.14114114,  0.14714715,
        0.15315315,  0.15915916,  0.16516517,  0.17117117,  0.17717718,
        0.18318318,  0.18918919,  0.1951952 ,  0.2012012 ,  0.20720721,
        0.21321321,  0.21921922,  0.22522523,  0.23123123,  0.23723724,
        0.24324324,  0.24924925,  0.25525526,  0.26126126,  0.26726727,
        0.27327327,  0.27927928,  0.28528529,  0.29129129,  0.2972973 ,
        0.3033033 ,  0.30930931,  0.31531532,  0.32132132,  0.32732733,
        0.33333333,  0.33933934,  0.34534535,  0.35135135,  0.35735736,
        0.36336336,  0.36936937,  0.37537538,  0.38138138,  0.38738739,
        0.39339339,  0.3993994 ,  0.40540541,  0.41141141,  0.41741742,
        0.42342342,  0.42942943,  0.43543544,  0.44144144,  0.44744745,
        0.45345345,  0.45945946,  0.46546547,  0.47147147,  0.47747748,
        0.48348348,  0.48948949,  0.4954955 ,  0.5015015 ,  0.50750751,
        0.51351351,  0.51951952,  0.52552553,  0.53153153,  0.53753754,
        0.54354354,  0.54954955,  0.55555556,  0.56156156,  0.56756757,
        0.57357357,  0.57957958,  0.58558559,  0.59159159,  0.5975976 ,
        0.6036036 ,  0.60960961,  0.61561562,  0.62162162,  0.62762763,
        0.63363363,  0.63963964,  0.64564565,  0.65165165,  0.65765766,
        0.66366366,  0.66966967,  0.67567568,  0.68168168,  0.68768769,
        0.69369369,  0.6996997 ,  0.70570571,  0.71171171,  0.71771772,
        0.72372372,  0.72972973,  0.73573574,  0.74174174,  0.74774775,
        0.75375375,  0.75975976,  0.76576577,  0.77177177,  0.77777778,
        0.78378378,  0.78978979,  0.7957958 ,  0.8018018 ,  0.80780781,
        0.81381381,  0.81981982,  0.82582583,  0.83183183,  0.83783784,
        0.84384384,  0.84984985,  0.85585586,  0.86186186,  0.86786787,
        0.87387387,  0.87987988,  0.88588589,  0.89189189,  0.8978979 ,
        0.9039039 ,  0.90990991,  0.91591592,  0.92192192,  0.92792793,
        0.93393393,  0.93993994,  0.94594595,  0.95195195,  0.95795796,
        0.96396396,  0.96996997,  0.97597598,  0.98198198,  0.98798799,
        0.99399399,  1.        ,  1.00600601,  1.01201201,  1.01801802,
        1.02402402,  1.03003003,  1.03603604,  1.04204204,  1.04804805,
        1.05405405,  1.06006006,  1.06606607,  1.07207207,  1.07807808,
        1.08408408,  1.09009009,  1.0960961 ,  1.1021021 ,  1.10810811,
        1.11411411,  1.12012012,  1.12612613,  1.13213213,  1.13813814,
        1.14414414,  1.15015015,  1.15615616,  1.16216216,  1.16816817,
        1.17417417,  1.18018018,  1.18618619,  1.19219219,  1.1981982 ,
        1.2042042 ,  1.21021021,  1.21621622,  1.22222222,  1.22822823,
        1.23423423,  1.24024024,  1.24624625,  1.25225225,  1.25825826,
        1.26426426,  1.27027027,  1.27627628,  1.28228228,  1.28828829,
        1.29429429,  1.3003003 ,  1.30630631,  1.31231231,  1.31831832,
        1.32432432,  1.33033033,  1.33633634,  1.34234234,  1.34834835,
        1.35435435,  1.36036036,  1.36636637,  1.37237237,  1.37837838,
        1.38438438,  1.39039039,  1.3963964 ,  1.4024024 ,  1.40840841,
        1.41441441,  1.42042042,  1.42642643,  1.43243243,  1.43843844,
        1.44444444,  1.45045045,  1.45645646,  1.46246246,  1.46846847,
        1.47447447,  1.48048048,  1.48648649,  1.49249249,  1.4984985 ,
        1.5045045 ,  1.51051051,  1.51651652,  1.52252252,  1.52852853,
        1.53453453,  1.54054054,  1.54654655,  1.55255255,  1.55855856,
        1.56456456,  1.57057057,  1.57657658,  1.58258258,  1.58858859,
        1.59459459,  1.6006006 ,  1.60660661,  1.61261261,  1.61861862,
        1.62462462,  1.63063063,  1.63663664,  1.64264264,  1.64864865,
        1.65465465,  1.66066066,  1.66666667,  1.67267267,  1.67867868,
        1.68468468,  1.69069069,  1.6966967 ,  1.7027027 ,  1.70870871,
        1.71471471,  1.72072072,  1.72672673,  1.73273273,  1.73873874,
        1.74474474,  1.75075075,  1.75675676,  1.76276276,  1.76876877,
        1.77477477,  1.78078078,  1.78678679,  1.79279279,  1.7987988 ,
        1.8048048 ,  1.81081081,  1.81681682,  1.82282282,  1.82882883,
        1.83483483,  1.84084084,  1.84684685,  1.85285285,  1.85885886,
        1.86486486,  1.87087087,  1.87687688,  1.88288288,  1.88888889,
        1.89489489,  1.9009009 ,  1.90690691,  1.91291291,  1.91891892,
        1.92492492,  1.93093093,  1.93693694,  1.94294294,  1.94894895,
        1.95495495,  1.96096096,  1.96696697,  1.97297297,  1.97897898,
        1.98498498,  1.99099099,  1.996997  ,  2.003003  ,  2.00900901,
        2.01501502,  2.02102102,  2.02702703,  2.03303303,  2.03903904,
        2.04504505,  2.05105105,  2.05705706,  2.06306306,  2.06906907,
        2.07507508,  2.08108108,  2.08708709,  2.09309309,  2.0990991 ,
        2.10510511,  2.11111111,  2.11711712,  2.12312312,  2.12912913,
        2.13513514,  2.14114114,  2.14714715,  2.15315315,  2.15915916,
        2.16516517,  2.17117117,  2.17717718,  2.18318318,  2.18918919,
        2.1951952 ,  2.2012012 ,  2.20720721,  2.21321321,  2.21921922,
        2.22522523,  2.23123123,  2.23723724,  2.24324324,  2.24924925,
        2.25525526,  2.26126126,  2.26726727,  2.27327327,  2.27927928,
        2.28528529,  2.29129129,  2.2972973 ,  2.3033033 ,  2.30930931,
        2.31531532,  2.32132132,  2.32732733,  2.33333333,  2.33933934,
        2.34534535,  2.35135135,  2.35735736,  2.36336336,  2.36936937,
        2.37537538,  2.38138138,  2.38738739,  2.39339339,  2.3993994 ,
        2.40540541,  2.41141141,  2.41741742,  2.42342342,  2.42942943,
        2.43543544,  2.44144144,  2.44744745,  2.45345345,  2.45945946,
        2.46546547,  2.47147147,  2.47747748,  2.48348348,  2.48948949,
        2.4954955 ,  2.5015015 ,  2.50750751,  2.51351351,  2.51951952,
        2.52552553,  2.53153153,  2.53753754,  2.54354354,  2.54954955,
        2.55555556,  2.56156156,  2.56756757,  2.57357357,  2.57957958,
        2.58558559,  2.59159159,  2.5975976 ,  2.6036036 ,  2.60960961,
        2.61561562,  2.62162162,  2.62762763,  2.63363363,  2.63963964,
        2.64564565,  2.65165165,  2.65765766,  2.66366366,  2.66966967,
        2.67567568,  2.68168168,  2.68768769,  2.69369369,  2.6996997 ,
        2.70570571,  2.71171171,  2.71771772,  2.72372372,  2.72972973,
        2.73573574,  2.74174174,  2.74774775,  2.75375375,  2.75975976,
        2.76576577,  2.77177177,  2.77777778,  2.78378378,  2.78978979,
        2.7957958 ,  2.8018018 ,  2.80780781,  2.81381381,  2.81981982,
        2.82582583,  2.83183183,  2.83783784,  2.84384384,  2.84984985,
        2.85585586,  2.86186186,  2.86786787,  2.87387387,  2.87987988,
        2.88588589,  2.89189189,  2.8978979 ,  2.9039039 ,  2.90990991,
        2.91591592,  2.92192192,  2.92792793,  2.93393393,  2.93993994,
        2.94594595,  2.95195195,  2.95795796,  2.96396396,  2.96996997,
        2.97597598,  2.98198198,  2.98798799,  2.99399399,  3.        ]),)

In [103]:

#08

import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
import math

mu = 0
variance = 1
sigma = math.sqrt(variance)
x = np.linspace(mu - 3*sigma, mu + 3*sigma, 1000)
plt.plot(x, stats.norm.pdf(x, mu, sigma))
plt.show()

In [111]:
# 08, 09
import numpy  as np 
import pandas as pd  # 偷用一下 

%matplotlib qt 
 

plt.rcParams['axes.prop_cycle']= plt.cycler( 
    color=['red',  
           'orange',  
           'yellow',  
           'green', 
           'cyan', 
           'blue', 
           'purple', 
           'magenta', 
           'gray', 
           'black']) 

def Normal(sampSize= 1000): 
     
    Y= pd.DataFrame(np.zeros((sampSize, 1))) 
    for i in range(0,8): 
        μ= i 
        σ= 1/2 
        Y[i]= np.random.normal(  
                loc=   μ,   
                scale= σ, 
                size= sampSize) 
    #Y=Y.cumsum() 
    Y.plot(alpha= .5, title= 'normal') 
    Y.hist() 
     
Normal(sampSize= 1000) 
